### PR TITLE
Angular 6 directives

### PR DESCRIPTION
**Pull request by dothework**
@jlhanl I have the selling points animating as hoped/planned. Please review the PR for differences. Note: location of jQuery script tag; points as data in the controller and not as a template, some tweaks to the directive.

### CODE REVIEW

**Comment by jlhanl** [comment]
Thanks, Mark. I took a look at your changes and merged your pull request so
I could look at the code locally... but the changes aren't appearing
locally for me for some reason. I've checked out master branch (where it
should have merged to) as well as angular-6-directives branch (where it
should have merged from), and neither is including your changes locally.

For now, I'm just going to reference your changes on git's web app. I don't
really know what to do about this unexpected git issue, and I can't find an
explanation of this behavior anywhere.

Thanks for taking the time to help me sort that part out... I think it will
help to have something to reference when applying this logic to the slider
directive.

Thanks,
Jenny

**Comment by dothework** [comment]
Hi Jen- it sounds like you have to pull the changes from GitHub to your local
folder. Could that be it?
A git pull is what you would do to bring a local branch up-to-date with its
remote version.

On Wed, Nov 11, 2015 at 11:50 AM, Jenny < notifications@github.com > wrote:
Thanks, Mark. I took a look at your changes and merged your pull request so
I could look at the code locally... but the changes aren't appearing
locally for me for some reason. I've checked out master branch (where it
should have merged to) as well as angular-6-directives branch (where it
should have merged from), and neither is including your changes locally.

For now, I'm just going to reference your changes on git's web app. I don't
really know what to do about this unexpected git issue, and I can't find an
explanation of this behavior anywhere.

Thanks for taking the time to help me sort that part out... I think it will
help to have something to reference when applying this logic to the slider
directive.

Thanks,
Jenny

On Tue, Nov 10, 2015 at 7:45 PM, dothework < notifications@github.com > wrote:

> @jlhanl < https://github.com/jlhanl > I have the selling points animating
> as hoped/planned. Please review the PR for differences. Note: location of
> jQuery script tag; points as data in the controller and not as a template,
> 
> ## some tweaks to the directive.
> 
> You can view, comment on, or merge this pull request online at:
> 
> https://github.com/jlhanl/ bloc-jams-angular2/pull/2
> Commit Summary
> - starting to add slider directive
> - Added jquery from old slider code
> - new directive approach
> - Selling Points exercise
> - selling-points
> 
> File Changes
> - _M_ app/pages/index.html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-0 > (5)
> - _M_ app/scripts/app.js
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-1 >
>   (110)
> - _M_ app/templates/album.html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-2 >
>   (10)
> - _M_ app/templates/landing.html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-3 >
>   (30)
> - _A_ app/templates/myslider.html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-4 > (4)
> - _A_ app/templates/sellingpoints. html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-5 >
>   (17)
> - _M_ dist/index.html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-6 > (5)
> - _M_ dist/scripts/app.js
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-7 >
>   (110)
> - _M_ dist/templates/album.html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-8 >
>   (10)
> - _M_ dist/templates/landing.html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-9 >
>   (30)
> - _A_ dist/templates/myslider.html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-10 >
>   (4)
> - _A_ dist/templates/sellingpoints. html
>   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-11 >
>   (17)
> 
> Patch Links:
> - https://github.com/jlhanl/ bloc-jams-angular2/pull/2. patch
> - https://github.com/jlhanl/ bloc-jams-angular2/pull/2.diff
> 
> —
> Reply to this email directly or view it on GitHub
> < https://github.com/jlhanl/ bloc-jams-angular2/pull/2 >.
> 
> —
> Reply to this email directly or view it on GitHub .

Not using Mixmax yet?

**Comment by jlhanl** [comment]
ohh! I didn't know that! phew... so, just `git pull`?

**Comment by dothework** [comment]
that's all. there are pull options but in this case - master to master - that's
all

On Wed, Nov 11, 2015 at 12:04 PM, Jenny < notifications@github.com > wrote:
ohh! I didn't know that! phew... so, just `git pull`?

On Wed, Nov 11, 2015 at 8:56 AM, dothework < notifications@github.com > wrote:

> Hi Jen- it sounds like you have to pull the changes from GitHub to your
> local
> folder. Could that be it?
> A git pull is what you would do to bring a local branch up-to-date with its
> remote version.
> 
> On Wed, Nov 11, 2015 at 11:50 AM, Jenny < notifications@github.com >
> wrote:
> Thanks, Mark. I took a look at your changes and merged your pull request so
> I could look at the code locally... but the changes aren't appearing
> locally for me for some reason. I've checked out master branch (where it
> should have merged to) as well as angular-6-directives branch (where it
> should have merged from), and neither is including your changes locally.
> 
> For now, I'm just going to reference your changes on git's web app. I don't
> really know what to do about this unexpected git issue, and I can't find an
> explanation of this behavior anywhere.
> 
> Thanks for taking the time to help me sort that part out... I think it will
> help to have something to reference when applying this logic to the slider
> directive.
> 
> Thanks,
> Jenny
> 
> On Tue, Nov 10, 2015 at 7:45 PM, dothework < notifications@github.com >
> wrote:
> 
> > @jlhanl < https://github.com/jlhanl > I have the selling points
> > animating
> > as hoped/planned. Please review the PR for differences. Note: location of
> > jQuery script tag; points as data in the controller and not as a
> > template,
> > 
> > ## some tweaks to the directive.
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/jlhanl/ bloc-jams-angular2/pull/2
> > Commit Summary
> > - starting to add slider directive
> > - Added jquery from old slider code
> > - new directive approach
> > - Selling Points exercise
> > - selling-points
> > 
> > File Changes
> > - _M_ app/pages/index.html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-0 >
> >   (5)
> > - _M_ app/scripts/app.js
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-1 >
> >   (110)
> > - _M_ app/templates/album.html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-2 >
> >   (10)
> > - _M_ app/templates/landing.html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-3 >
> >   (30)
> > - _A_ app/templates/myslider.html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-4 >
> >   (4)
> > - _A_ app/templates/sellingpoints. html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-5 >
> >   (17)
> > - _M_ dist/index.html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-6 >
> >   (5)
> > - _M_ dist/scripts/app.js
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-7 >
> >   (110)
> > - _M_ dist/templates/album.html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-8 >
> >   (10)
> > - _M_ dist/templates/landing.html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-9 >
> >   (30)
> > - _A_ dist/templates/myslider.html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-10 >
> >   (4)
> > - _A_ dist/templates/sellingpoints. html
> >   < https://github.com/jlhanl/ bloc-jams-angular2/pull/2/ files#diff-11 >
> >   (17)
> > 
> > Patch Links:
> > - https://github.com/jlhanl/ bloc-jams-angular2/pull/2. patch
> > - https://github.com/jlhanl/ bloc-jams-angular2/pull/2.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > < https://github.com/jlhanl/ bloc-jams-angular2/pull/2 >.
> > 
> > —
> > Reply to this email directly or view it on GitHub .
> 
> Not using Mixmax yet?
> 
> —
> Reply to this email directly or view it on GitHub
> < https://github.com/jlhanl/ bloc-jams-angular2/pull/2# issuecomment-155845486 >
> .
> 
> —
> Reply to this email directly or view it on GitHub .

Not using Mixmax yet?

**Comment by jlhanl** [comment]
thank you... that all makes much more sense.

**Pull request merged**
